spring:
  application:
    name: revenue-assurance
  datasource:
    url: jdbc:postgresql://localhost:5432/ra
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8080

# Настройки для ClickHouse
clickhouse:
  url: jdbc:clickhouse://localhost:8124/ra_analytics
  username: default
  password:
  database: ra_analytics
  enabled: false # Отключаем ClickHouse для локальной разработки, если сервер не запущен

# Настройки для мониторинга файлов
app:
  file-watcher:
    input-dir: data/input
    done-dir: data/done
    error-dir: data/error
    file-pattern: "*.csv"
    interval: 1000
    enabled: true 
