CREATE DATABASE IF NOT EXISTS ra_analytics;

CREATE TABLE IF NOT EXISTS ra_analytics.transactions
(
    id UUID,
    sender_msisdn String,
    receiver_msisdn String,
    receiver_user_id String,
    sender_user_id String,
    transaction_amount Decimal(19, 2),
    commissions_paid Decimal(19, 2),
    commissions_received Decimal(19, 2),
    commissions_others Decimal(19, 2),
    service_charge_received Decimal(19, 2),
    service_charge_paid Decimal(19, 2),
    taxes Decimal(19, 2),
    service_type String,
    transfer_status String,
    sender_pre_bal Decimal(19, 2),
    sender_post_bal Decimal(19, 2),
    receiver_pre_bal Decimal(19, 2),
    receiver_post_bal Decimal(19, 2),
    sender_acc_status String,
    receiver_acc_status String,
    error_code String,
    error_desc String,
    reference_number String,
    created_on DateTime,
    created_by String,
    modified_on DateTime,
    modified_by String,
    app_1_date DateTime,
    app_2_date DateTime,
    transfer_id String,
    transfer_datetime DateTime,
    sender_category_code String,
    sender_domain_code String,
    sender_grade_name String,
    sender_group_role String,
    sender_designation String,
    sender_state String,
    receiver_category_code String,
    receiver_domain_code String,
    receiver_grade_name String,
    receiver_group_role String,
    receiver_designation String,
    receiver_state String,
    sender_city String,
    receiver_city String,
    app_1_by String,
    app_2_by String,
    request_source String,
    gateway_type String,
    transfer_subtype String,
    payment_type String,
    payment_number String,
    payment_date DateTime,
    remarks String,
    action_type String,
    transaction_tag String,
    reconciliation_by String,
    reconciliation_for String,
    ext_txn_number String,
    original_ref_number String,
    zebra_ambiguous String,
    attempt_status String,
    other_msisdn String,
    sender_wallet_number String,
    receiver_wallet_number String,
    sender_user_name String,
    receiver_user_name String,
    tno_msisdn String,
    tno_id String,
    unreg_first_name String,
    unreg_last_name String,
    unreg_dob Date,
    unreg_id_number String,
    bulk_payout_batchid String,
    is_financial String,
    transfer_done String,
    initiator_msisdn String,
    validator_msisdn String,
    initiator_comments String,
    validator_comments String,
    sender_wallet_name String,
    reciever_wallet_name String,
    sender_user_type String,
    receiver_user_type String,
    txnmode String,
    file_upload_id UUID,
    load_timestamp DateTime
)
ENGINE = MergeTree()
ORDER BY (transfer_datetime, sender_msisdn, receiver_msisdn)
PARTITION BY toYYYYMM(transfer_datetime); 